### ISSUE TITLE
Third display getting lost of display position

### ISSUE THREAD

**Issue by jwdotpark** [GnomeSnapExtensions/gSnap#77]
Hi, thank you for the great extension! 

I have a bug regarding third display not being recognized after a while(not sure what event cause losing the display setup). It only happens on third display, I assume this [code](https://github.com/GnomeSnapExtensions/gSnap/blob/6fffcdc5fae908b50591fd8130ca093c3e9dd960/src/extension/monitors.ts#L36C44-L36C44) is related to it. 

If I manually designate the value to monitor3, it does work as intended a while but like I said above, it lose its position value as soon as there is an event such as changing focus, triggering application grid or some kind of fullscreen event it seems. 

I'll try making the fix but guess it's worth reporting. Again, thank you for the great extension!

**Comment by thomas-rooty** [comment]
Hi,

I also have this bug, I have 3 monitors and the middle one which is number 3 on the gSnap point of view doesnt remember its grid layout.

**Comment by jwdotpark** [comment]
@meronz Hey I'm so sorry for late response, I completely forgot about the bug report! 

My description went wrong a bit - what I meant was the extension doesn't recognize the display more than 2 basically. 

![image](https://github.com/GnomeSnapExtensions/gSnap/assets/38537908/d961e88e-b1b6-41e9-a8da-7d3820874804)

To be precise, the extension does recognize every display but only 2 displays are ready for tiling, more than 2 display are ignored regardless of display array in below setup.

![image](https://github.com/GnomeSnapExtensions/gSnap/assets/38537908/d5f6d966-34d5-4a6e-a779-db0be9c5dab8)

Apologize for this frankenstein but with the setup above for an example, again only 2 display can be tiled no matter what. Also the order is random so I have to do the enable/disable puzzle in the Settings for designated display being able to be tiled (in my case 1 and 3) but that's rather gnome display array management thing than this extension(Sorry I can't be sure).

I tried logging using `journalctl --follow /usr/bin/gnome-shell | grep "gSnap"` but I can't see any log while tiling, not sure what went wrong. I haven't been involved in gnome env development before, any cursor for debugging would be very much appreciated.  

All in all it works as intended once I get it right for 2 displays and I don't have much problem for now, priority for this one is pretty low tbh. Thanks for the great extension!

**Comment by meronz** [comment]
Don't worry! To enable the logs you need to go in the extensions settings and click on the "debug" checkbox. If you can provide the logs I could try to fix it :)

**Comment by jwdotpark** [comment]
- `Display 1`: 2560*1080, landscape
- `Display 2`: 1680*1050, portrait right
- `Display 3`: 3440*1440, landscape

In the process of logging, tiling is only applied to display 1 and 3. If I change the layout of display array in the Settings, tiling applied display is changed randomly.

Here's the [log.txt](https://github.com/GnomeSnapExtensions/gSnap/files/14013213/log.txt) when I enabled `Display 2` out of all 3 displays. All the log is generated from the process of enabling the display except last line which is just moving window from A to B. 

I'm not sure this is appropriate way to reproduce the bug. If you want any different way situation to try, please let me know I'd happy to provide more.

**Comment by warelock2** [comment]
I'm having this same issue with my third monitor. I just enabled debugging and hope to see definite errors in the log when the problem happens again.

**Comment by warelock2** [comment]
@meronz I have a three monitor setup. The systray drop down menu shows three monitors, enumerated as 0, 1, and 2. However as you can see, this plugin only supports saving configuration for two monitors.

`$ jq -r '.workspaces[0]' ~/.config/gSnap/layouts.json
[
  {
    "current": 1
  },
  {
    "current": 1
  }
]`

A user is free to configure the third monitor, but if they make * any * change in Settings, the plugin restarts itself, reloading configuration from the json file. Since no settings were saved for the third monitor, the third monitor loses its configuration and must be manually set again by the user.

To watch this plugin save your changes to disk, live:

`$ watch jq -r '.workspaces[0]' ~/.config/gSnap/layouts.json`

This looks like an oversight on the developer's part. This plugin obviously supports n monitors. Please at least support three monitors. Please also fix the code to save the configuration of the third monitor to the json file, just like it already does for the first two monitors. Thanks.

**Comment by warelock2** [comment]
Here's a one-time workaround hack you can do live:

This a three-monitor fix, setting layout "0" or "None" for all three monitors. You can just copy/paste the code into your non-root shell:

```
json_file=~/.config/gSnap/layouts.json
content=$(cat $json_file | jq -r ".workspaces =
    [
      [
        {"current": 0},
        {"current": 0},
        {"current": 0}
      ],
      [
        {"current": 0},
        {"current": 0},
        {"current": 0}
      ]
    ]"
)
echo $content | jq -r . > $json_file
```

Once this is done, just go into the extension drop down menu and set your monitors to the layouts you want, as you normally would. Since this code does an in-line edit your existing "layouts.json" file, any custom layouts you may have created shouldn't be altered at all.

As to the original problem, my investigations have shown me that the code that creates the default "layouts.json" file assume you have two monitors, rather than probe what you do have (ie. three monitors) and create the initial "layouts.json" file properly. If you actually have three monitors and the "layouts.json" file only is set up for two monitors, the settings for your third monitor will be lost whenever you make any changes in the extension per-monitor layout assignments or settings.

@meronz Please fix this. Thanks.

**Comment by meronz** [comment]
Fixed, please wait for the extension to be released on EGO.
